name: Build (dev)

on:
  push:
    branches:
      - dev
env:
  RUN_UNIT_TEST: 'false'
  RUN_SONARQUBE: 'false'

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
      envvalue2: ${{ steps.setvar.outputs.envvar2 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo "::set-output name=envvar1::$RUN_UNIT_TEST" 
          echo "::set-output name=envvar2::$RUN_SONARQUBE"

  test-job:
    if: ${{ needs.initialization.outputs.envvalue1=='true' }}
    uses: ./.github/workflows/1_test.yml
    needs: [initialization]

  sonarqube-job:
    if: ${{ success() && needs.initialization.outputs.envvalue2=='true' }}
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    #needs: [test-job]

  cd-job:
    if: ${{ success() || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='false') }}
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: 'ecap3-webclient-$SERVICE_NAME'
      NAMESPACE: 'dev-spiga'
      SERVICE_VALUE: "spiga-adventgames-webclient"
      CI_BUILD: 'build-prod'
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.SPIGA_AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.SPIGA_ACR }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.SPIGA_RG }}
      CLUSTER_NAME: ${{ secrets.SPIGA_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.SPIGA_RG }}
    # needs: [sonarqube-job]
