name: Build (main)

on:
  push:
    branches:
      - main
env:
  RUN_UNIT_TEST: 'false'
  RUN_SONARQUBE: 'false'

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
      envvalue2: ${{ steps.setvar.outputs.envvar2 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo "::set-output name=envvar1::$RUN_UNIT_TEST" 
          echo "::set-output name=envvar2::$RUN_SONARQUBE"
  test-job:
    if: ${{ needs.initialization.outputs.envvalue1=='true' || (github.event_name == 'pull_request' && github.head_ref != 'stg') }}
    uses: ./.github/workflows/1_test.yml
    needs: [initialization]

  sonarqube-job:
    if: ${{ success() && needs.initialization.outputs.envvalue2=='true' || (github.event_name == 'pull_request' && github.head_ref != 'stg') }}
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    #needs: [test-job]

  cd-job:
    if: ${{ success() || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='false') }}
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: 'prod-ecap3-webclient-$SERVICE_NAME'
      NAMESPACE: 'prod-$SERVICE_NAME'
      SERVICE_NAME: $SERVICE_NAME
      CI_BUILD: 'build:ci:prod'
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.PROD_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}
    # needs: [sonarqube-job]